# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UnityGetProjectVersionTask@1

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Install-Module -Name UnitySetup -AllowPrerelease -Scope CurrentUser -Force'
    failOnStderr: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Install-UnitySetupInstance -Installers (Find-UnitySetupInstaller -Version ''$(unitygetprojectversion.projectVersion)'' -Components Windows,Windows_IL2CPP) -Verbose'
    failOnStderr: true
- task: UnityActivateLicenseTask@1
  inputs:
    username: 'michael@eolianvr.com'
    password: 'Kg4bjoarre'
    serial: 'SC-T3QA-2QAR-Q2GQ-7662-BX3H'
    unityEditorsPathMode: 'unityHub'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.BinariesDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'